version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/sesha3/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/sesha3/scripts
    pattern: "*.sh"
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 10
      runas: root
